aria2c -o "Afghanistan.svg" "https://upload.wikimedia.org/wikipedia/commons/5/5c/Flag_of_the_Taliban.svg"
aria2c -o "Armenia.svg" "https://upload.wikimedia.org/wikipedia/commons/2/2f/Flag_of_Armenia.svg"
aria2c -o "Azerbaijan.svg" "https://upload.wikimedia.org/wikipedia/commons/d/dd/Flag_of_Azerbaijan.svg"
aria2c -o "Bahrain.svg" "https://upload.wikimedia.org/wikipedia/commons/2/2c/Flag_of_Bahrain.svg"
aria2c -o "Bangladesh.svg" "https://upload.wikimedia.org/wikipedia/commons/f/f9/Flag_of_Bangladesh.svg"
aria2c -o "Bhutan.svg" "https://upload.wikimedia.org/wikipedia/commons/9/91/Flag_of_Bhutan.svg"
aria2c -o "Brunei.svg" "https://upload.wikimedia.org/wikipedia/commons/9/9c/Flag_of_Brunei.svg"
aria2c -o "Cambodia.svg" "https://upload.wikimedia.org/wikipedia/commons/8/83/Flag_of_Cambodia.svg"
aria2c -o "China.svg" "https://upload.wikimedia.org/wikipedia/commons/f/fa/Flag_of_the_People%27s_Republic_of_China.svg"
aria2c -o "India.svg" "https://upload.wikimedia.org/wikipedia/en/4/41/Flag_of_India.svg"
aria2c -o "Indonesia.svg" "https://upload.wikimedia.org/wikipedia/commons/9/9f/Flag_of_Indonesia.svg"
aria2c -o "Iran.svg" "https://upload.wikimedia.org/wikipedia/commons/c/ca/Flag_of_Iran.svg"
aria2c -o "Iraq.svg" "https://upload.wikimedia.org/wikipedia/commons/f/f6/Flag_of_Iraq.svg"
aria2c -o "Israel.svg" "https://upload.wikimedia.org/wikipedia/commons/d/d4/Flag_of_Israel.svg"
aria2c -o "Japan.svg" "https://upload.wikimedia.org/wikipedia/en/9/9e/Flag_of_Japan.svg"
aria2c -o "Jordan.svg" "https://upload.wikimedia.org/wikipedia/commons/c/c0/Flag_of_Jordan.svg"
aria2c -o "Kazakhstan.svg" "https://upload.wikimedia.org/wikipedia/commons/d/d3/Flag_of_Kazakhstan.svg"
aria2c -o "Kuwait.svg" "https://upload.wikimedia.org/wikipedia/commons/a/aa/Flag_of_Kuwait.svg"
aria2c -o "Kyrgyzstan.svg" "https://upload.wikimedia.org/wikipedia/commons/c/c7/Flag_of_Kyrgyzstan.svg"
aria2c -o "Laos.svg" "https://upload.wikimedia.org/wikipedia/commons/5/56/Flag_of_Laos.svg"
aria2c -o "Lebanon.svg" "https://upload.wikimedia.org/wikipedia/commons/5/59/Flag_of_Lebanon.svg"
aria2c -o "Malaysia.svg" "https://upload.wikimedia.org/wikipedia/commons/6/66/Flag_of_Malaysia.svg"
aria2c -o "Maldives.svg" "https://upload.wikimedia.org/wikipedia/commons/0/0f/Flag_of_Maldives.svg"
aria2c -o "Mongolia.svg" "https://upload.wikimedia.org/wikipedia/commons/4/4c/Flag_of_Mongolia.svg"
aria2c -o "Myanmar.svg" "https://upload.wikimedia.org/wikipedia/commons/8/8c/Flag_of_Myanmar.svg"
aria2c -o "Nepal.svg" "https://upload.wikimedia.org/wikipedia/commons/9/9b/Flag_of_Nepal.svg"
aria2c -o "North Korea.svg" "https://upload.wikimedia.org/wikipedia/commons/5/51/Flag_of_North_Korea.svg"
aria2c -o "Oman.svg" "https://upload.wikimedia.org/wikipedia/commons/d/dd/Flag_of_Oman.svg"
aria2c -o "Pakistan.svg" "https://upload.wikimedia.org/wikipedia/commons/3/32/Flag_of_Pakistan.svg"
aria2c -o "Palestine.svg" "https://upload.wikimedia.org/wikipedia/commons/0/00/Flag_of_Palestine.svg"
aria2c -o "Philippines.svg" "https://upload.wikimedia.org/wikipedia/commons/9/99/Flag_of_the_Philippines.svg"
aria2c -o "Qatar.svg" "https://upload.wikimedia.org/wikipedia/commons/6/65/Flag_of_Qatar.svg"
aria2c -o "Saudi Arabia.svg" "https://upload.wikimedia.org/wikipedia/commons/0/0d/Flag_of_Saudi_Arabia.svg"
aria2c -o "Singapore.svg" "https://upload.wikimedia.org/wikipedia/commons/4/48/Flag_of_Singapore.svg"
aria2c -o "South Korea.svg" "https://upload.wikimedia.org/wikipedia/commons/0/09/Flag_of_South_Korea.svg"
aria2c -o "Sri Lanka.svg" "https://upload.wikimedia.org/wikipedia/commons/1/11/Flag_of_Sri_Lanka.svg"
aria2c -o "Syria.svg" "https://upload.wikimedia.org/wikipedia/commons/5/54/Flag_of_Syria_%282025-%29.svg"
aria2c -o "Tajikistan.svg" "https://upload.wikimedia.org/wikipedia/commons/d/d0/Flag_of_Tajikistan.svg"
aria2c -o "Thailand.svg" "https://upload.wikimedia.org/wikipedia/commons/a/a9/Flag_of_Thailand.svg"
aria2c -o "Timor-Leste.svg" "https://upload.wikimedia.org/wikipedia/commons/2/26/Flag_of_East_Timor.svg"
aria2c -o "Turkey.svg" "https://upload.wikimedia.org/wikipedia/commons/b/b4/Flag_of_Turkey.svg"
aria2c -o "Turkmenistan.svg" "https://upload.wikimedia.org/wikipedia/commons/1/1b/Flag_of_Turkmenistan.svg"
aria2c -o "United Arab Emirates.svg" "https://upload.wikimedia.org/wikipedia/commons/c/cb/Flag_of_the_United_Arab_Emirates.svg"
aria2c -o "Uzbekistan.svg" "https://upload.wikimedia.org/wikipedia/commons/8/84/Flag_of_Uzbekistan.svg"
aria2c -o "Vietnam.svg" "https://upload.wikimedia.org/wikipedia/commons/2/21/Flag_of_Vietnam.svg"
aria2c -o "Yemen.svg" "https://upload.wikimedia.org/wikipedia/commons/8/89/Flag_of_Yemen.svg"
aria2c -o "Taiwan.svg" "https://upload.wikimedia.org/wikipedia/commons/7/72/Flag_of_the_Republic_of_China.svg"