const regions = {

  asia: [
    { key: "armenia", label: "Armenia" },
    { key: "azerbaijan", label: "Azerbaijan" },
    { key: "bahrain", label: "Bahrain" },
    { key: "bangladesh", label: "Bangladesh" },
    { key: "bhutan", label: "Bhutan" },
    { key: "india", label: "India" },

    { key: "brunei", label: "Brunei" },
    { key: "cambodia", label: "Cambodia" },
    { key: "china", label: "China" },
    { key: "united-arab-emirates", label: "UAE" },
    { key: "uzbekistan", label: "Uzbekistan" },
    { key: "indonesia", label: "Indonesia" },

    { key: "iran", label: "Iran" },
    { key: "iraq", label: "Iraq" },
    { key: "japan", label: "Japan" },
    { key: "jordan", label: "Jordan" },
    { key: "kuwait", label: "Kuwait" },
    { key: "kyrgyzstan", label: "Kyrgyzstan" },

    { key: "laos", label: "Laos" },
    { key: "lebanon", label: "Lebanon" },
    { key: "malaysia", label: "Malaysia" },
    { key: "maldives", label: "Maldives" },
    { key: "vietnam", label: "Vietnam" },
    { key: "myanmar", label: "Myanmar" },

    { key: "nepal", label: "Nepal" },
    { key: "north-korea", label: "North Korea" },
    { key: "oman", label: "Oman" },
    { key: "pakistan", label: "Pakistan" },
    { key: "palestine", label: "Palestine" },
    { key: "philippines", label: "Philippines" },

    { key: "qatar", label: "Qatar" },
    { key: "saudi-arabia", label: "Saudi Arabia" },
    { key: "thailand", label: "Thailand" },
    { key: "timor-leste", label: "Timor-Leste" },
    { key: "yemen", label: "Yemen" },
    { key: "hong-kong", label: "Hong Kong" },

    { key: "singapore", label: "Singapore" },
    { key: "south-korea", label: "South Korea" },
    { key: "macau", label: "Macau" },
    { key: "syria", label: "Syria" },
    { key: "taiwan", label: "Taiwan" },
    { key: "tajikistan", label: "Tajikistan" },

    { key: "turkmenistan", label: "Turkmenistan" },
    { key: "israel", label: "Israel" },
    { key: "kazakhstan", label: "Kazakhstan" },
    { key: "turkey", label: "Turkey" },
    { key: "mongolia", label: "Mongolia" },

    { key: "cocos-islands", label: "Cocos Islands" },
    { key: "christmas-island", label: "Christmas Island" },
    { key: "afghanistan", label: "Afghanistan" },
    { key: "sri-lanka", label: "Sri Lanka" },
  ],

  europe: [
    { key: "italy", label: "Italy" },
    { key: "sweden", label: "Sweden" },
    { key: "switzerland", label: "Switzerland" },
    { key: "albania", label: "Albania" },
    { key: "andorra", label: "Andorra" },
    { key: "belarus", label: "Belarus" },
    { key: "croatia", label: "Croatia" },
    { key: "luxembourg", label: "Luxembourg" },
    { key: "monaco", label: "Monaco" },
    { key: "kosovo", label: "Kosovo" },
    { key: "liechtenstein", label: "Liechtenstein" },

    { key: "ireland", label: "Ireland" },
    { key: "ukraine", label: "Ukraine" },
    { key: "united-kingdom", label: "United Kingdom" },
    { key: "macedonia", label: "North Macedonia" },
    { key: "poland", label: "Poland" },
    { key: "montenegro", label: "Montenegro" },
    { key: "portugal", label: "Portugal" },
    { key: "russia", label: "Russia" },
    { key: "romania", label: "Romania" },
    { key: "serbia", label: "Serbia" },
    { key: "slovenia", label: "Slovenia" },

    { key: "guernsey", label: "Guernsey" },
    { key: "slovakia", label: "Slovakia" },
    { key: "spain", label: "Spain" },
    { key: "denmark", label: "Denmark" },
    { key: "vatican-city", label: "Vatican City" },
    { key: "norway", label: "Norway" },
    { key: "austria", label: "Austria" },
    { key: "netherlands", label: "Netherlands" },
    { key: "belgium", label: "Belgium" },
    { key: "bulgaria", label: "Bulgaria" },
    { key: "bosnia-and-herzegovina", label: "Bosnia & Herzegovina" },

    { key: "georgia", label: "Georgia" },
    { key: "estonia", label: "Estonia" },
    { key: "finland", label: "Finland" },
    { key: "france", label: "France" },
    { key: "germany", label: "Germany" },
    { key: "greece", label: "Greece" },
    { key: "hungary", label: "Hungary" },
    { key: "iceland", label: "Iceland" },

    { key: "cyprus", label: "Cyprus" },
    { key: "san-marino", label: "San Marino" },
    { key: "czechia", label: "Czechia" },
    { key: "latvia", label: "Latvia" },
    { key: "lithuania", label: "Lithuania" },
    { key: "malta", label: "Malta" },
    { key: "moldova", label: "Moldova" }
  ],

  africa: [
    { key: "malawi", label: "Malawi" },
    { key: "gambia", label: "Gambia" },
    { key: "central-african-republic", label: "Central African Republic" },
    { key: "uganda", label: "Uganda" },
    { key: "chad", label: "Chad" },
    { key: "senegal", label: "Senegal" },
    { key: "mali", label: "Mali" },
    { key: "ghana", label: "Ghana" },

    { key: "cabo-verde", label: "Cabo Verde" },
    { key: "cameroon", label: "Cameroon" },
    { key: "burundi", label: "Burundi" },
    { key: "burkina-faso", label: "Burkina Faso" },
    { key: "botswana", label: "Botswana" },
    { key: "benin", label: "Benin" },
    { key: "angola", label: "Angola" },
    { key: "algeria", label: "Algeria" },

    { key: "gabon", label: "Gabon" },
    { key: "ethiopia", label: "Ethiopia" },
    { key: "eritrea", label: "Eritrea" },
    { key: "equatorial-guinea", label: "Equatorial Guinea" },
    { key: "djibouti", label: "Djibouti" },
    { key: "republic-of-the-congo", label: "Republic of the Congo" },
    { key: "democratic-republic-of-the-congo", label: "DR Congo" },
    { key: "comoros", label: "Comoros" },

    { key: "madagascar", label: "Madagascar" },
    { key: "libya", label: "Libya" },
    { key: "liberia", label: "Liberia" },
    { key: "lesotho", label: "Lesotho" },
    { key: "kenya", label: "Kenya" },
    { key: "cote-divoire", label: "Cote d'Ivoire" },
    { key: "guinea-bissau", label: "Guinea-Bissau" },
    { key: "guinea", label: "Guinea" },

    { key: "rwanda", label: "Rwanda" },
    { key: "nigeria", label: "Nigeria" },
    { key: "niger", label: "Niger" },
    { key: "namibia", label: "Namibia" },
    { key: "mozambique", label: "Mozambique" },
    { key: "morocco", label: "Morocco" },
    { key: "mauritius", label: "Mauritius" },
    { key: "mauritania", label: "Mauritania" },
    { key: "sudan", label: "Sudan" },

    { key: "togo", label: "Togo" },
    { key: "tanzania", label: "Tanzania" },
    { key: "eswatini", label: "Eswatini" },
    { key: "south-africa", label: "South Africa" },
    { key: "somalia", label: "Somalia" },
    { key: "zimbabwe", label: "Zimbabwe" },
    { key: "sierra-leone", label: "Sierra Leone" },
    { key: "seychelles", label: "Seychelles" },

    { key: "tunisia", label: "Tunisia" },
    { key: "sao-tome-and-principe", label: "Sao Tome and Principe" },
    { key: "south-sudan", label: "South Sudan" },
    { key: "egypt", label: "Egypt" },
    { key: "western-sahara", label: "Western Sahara" },
    { key: "zambia", label: "Zambia" },
    { key: "mayotte", label: "Mayotte" },
    { key: "reunion", label: "Reunion" }
  ],

"north-america": [
  { key: "martinique", label: "Martinique" },
  { key: "saint-barthelemy", label: "Saint Barthelemy" },
  { key: "cayman-islands", label: "Cayman Islands" },
  { key: "montserrat", label: "Montserrat" },
  { key: "anguilla", label: "Anguilla" },
  { key: "british-virgin-islands", label: "British Virgin Islands" },
  { key: "turks-and-caicos", label: "Turks and Caicos" },

  { key: "saint-vincent-and-the-grenadines", label: "Saint Vincent and the Grenadines" },
  { key: "puerto-rico", label: "Puerto Rico" },
  { key: "united-states", label: "United States" },
  { key: "antigua-and-barbuda", label: "Antigua and Barbuda" },
  { key: "bahamas", label: "Bahamas" },
  { key: "barbados", label: "Barbados" },
  { key: "belize", label: "Belize" },
  { key: "canada", label: "Canada" },

  { key: "panama", label: "Panama" },
  { key: "saint-kitts-and-nevis", label: "Saint Kitts and Nevis" },
  { key: "saint-lucia", label: "Saint Lucia" },
  { key: "cuba", label: "Cuba" },
  { key: "costa-rica", label: "Costa Rica" },
  { key: "dominica", label: "Dominica" },
  { key: "dominican-republic", label: "Dominican Republic" },
  { key: "el-salvador", label: "El Salvador" },

  { key: "trinidad-and-tobago", label: "Trinidad and Tobago" },
  { key: "greenland", label: "Greenland" },
  { key: "nicaragua", label: "Nicaragua" },
  { key: "mexico", label: "Mexico" },
  { key: "grenada", label: "Grenada" },
  { key: "guatemala", label: "Guatemala" },
  { key: "haiti", label: "Haiti" },
  { key: "honduras", label: "Honduras" },
  { key: "jamaica", label: "Jamaica" }
],

"south-america": [
  { key: "argentina", label: "Argentina" },
  { key: "brazil", label: "Brazil" },
  { key: "colombia", label: "Colombia" },
  { key: "curacao", label: "Curacao" },

  { key: "guiana", label: "Guiana" },
  { key: "peru", label: "Peru" },
  { key: "suriname", label: "Suriname" },
  { key: "uruguay", label: "Uruguay" },

  { key: "venezuela", label: "Venezuela" },
  { key: "bolivia", label: "Bolivia" },
  { key: "chile", label: "Chile" },
  { key: "falkland-islands", label: "Falkland Islands" },

  { key: "ecuador", label: "Ecuador" },
  { key: "guyana", label: "Guyana" },
  { key: "paraguay", label: "Paraguay" },
  { key: "aruba", label: "Aruba" }
],

oceania: [
  { key: "palau", label: "Palau" },
  { key: "guam", label: "Guam" },
  { key: "marshall-islands", label: "Marshall Islands" },

  { key: "papua-new-guinea", label: "Papua New Guinea" },
  { key: "solomon-islands", label: "Solomon Islands" },
  { key: "kiribati", label: "Kiribati" },

  { key: "fiji", label: "Fiji" },
  { key: "cook-islands", label: "Cook Islands" },
  { key: "french-polynesia", label: "French Polynesia" },

  { key: "new-zealand", label: "New Zealand" },
  { key: "tonga", label: "Tonga" },
  { key: "vanuatu", label: "Vanuatu" },

  { key: "nauru", label: "Nauru" },
  { key: "niue", label: "Niue" },
  { key: "tuvalu", label: "Tuvalu" },

  { key: "micronesia", label: "Micronesia" },
  { key: "new-caledonia", label: "New Caledonia" },
  { key: "pitcairn-islands", label: "Pitcairn Islands" },

  { key: "samoa", label: "Samoa" },
  { key: "american-samoa", label: "American Samoa" },
  { key: "australia", label: "Australia" }
]



};
